m00 = Airport.create! ({ :iata => "AAC", :name => "El Arish International Airport"})
m00 = Airport.create! ({ :iata => "AAN", :name => "Al Ain International Airport"})
m00 = Airport.create! ({ :iata => "AAY", :name => "Al Ghaidah International Airport"})
m00 = Airport.create! ({ :iata => "ABB", :name => "Asaba International Airport"})
m00 = Airport.create! ({ :iata => "ABE", :name => "Lehigh Valley International Airport"})
m00 = Airport.create! ({ :iata => "ABQ", :name => "Albuquerque International Sunport Airport"})
m00 = Airport.create! ({ :iata => "ABV", :name => "Nnamdi Azikiwe International Airport"})
m00 = Airport.create! ({ :iata => "ACA", :name => "General Juan N Alvarez International Airport"})
m00 = Airport.create! ({ :iata => "ACC", :name => "Kotoka International Airport"})
m00 = Airport.create! ({ :iata => "ACY", :name => "Atlantic City International Airport"})
m00 = Airport.create! ({ :iata => "ADB", :name => "Adnan Menderes International Airport"})
m00 = Airport.create! ({ :iata => "ADD", :name => "Bole International Airport"})
m00 = Airport.create! ({ :iata => "ADE", :name => "Aden International Airport"})
m00 = Airport.create! ({ :iata => "ADJ", :name => "Amman-Marka International Airport"})
m00 = Airport.create! ({ :iata => "ADL", :name => "Adelaide International Airport"})
m00 = Airport.create! ({ :iata => "ADZ", :name => "Gustavo Rojas Pinilla International Airport"})
m00 = Airport.create! ({ :iata => "AER", :name => "Sochi International Airport"})
m00 = Airport.create! ({ :iata => "AEX", :name => "Alexandria International Airport"})
m00 = Airport.create! ({ :iata => "AGT", :name => "Guarani International Airport"})
m00 = Airport.create! ({ :iata => "AGU", :name => "Jesus Teran International Airport"})
m00 = Airport.create! ({ :iata => "AJY", :name => "Mano Dayak International Airport"})
m00 = Airport.create! ({ :iata => "AKC", :name => "Akron Fulton International Airport"})
m00 = Airport.create! ({ :iata => "AKL", :name => "Auckland International Airport"})
m00 = Airport.create! ({ :iata => "ALB", :name => "Albany International Airport"})
m00 = Airport.create! ({ :iata => "ALC", :name => "Alicante International Airport"})
m00 = Airport.create! ({ :iata => "ALI", :name => "Alice International Airport"})
m00 = Airport.create! ({ :iata => "ALL", :name => "Villanova D Albenga International Airport"})
m00 = Airport.create! ({ :iata => "ALP", :name => "Aleppo International Airport"})
m00 = Airport.create! ({ :iata => "AMA", :name => "Rick Husband Amarillo International Airport"})
m00 = Airport.create! ({ :iata => "AMD", :name => "Sardar Vallabhbhai Patel International Airport"})
m00 = Airport.create! ({ :iata => "AMM", :name => "Queen Alia International Airport"})
m00 = Airport.create! ({ :iata => "ANC", :name => "Ted Stevens Anchorage International Airport"})
m00 = Airport.create! ({ :iata => "ANR", :name => "Antwerp International Airport (Deurne)"})
m00 = Airport.create! ({ :iata => "ANU", :name => "V.C. Bird International Airport"})
m00 = Airport.create! ({ :iata => "APW", :name => "Faleolo International Airport"})
m00 = Airport.create! ({ :iata => "AQJ", :name => "Aqaba King Hussein International Airport"})
m00 = Airport.create! ({ :iata => "ART", :name => "Watertown International Airport"})
m00 = Airport.create! ({ :iata => "ARW", :name => "Arad International Airport"})
m00 = Airport.create! ({ :iata => "ASA", :name => "Assab International Airport"})
m00 = Airport.create! ({ :iata => "ASM", :name => "Asmara International Airport"})
m00 = Airport.create! ({ :iata => "ASU", :name => "Silvio Pettirossi International Airport"})
m00 = Airport.create! ({ :iata => "ASW", :name => "Aswan International Airport"})
m00 = Airport.create! ({ :iata => "ATH", :name => "Eleftherios Venizelos International Airport"})
m00 = Airport.create! ({ :iata => "ATI", :name => "Artigas International Airport"})
m00 = Airport.create! ({ :iata => "ATL", :name => "Hartsfield Jackson Atlanta International Airport"})
m00 = Airport.create! ({ :iata => "ATQ", :name => "Sri Guru Ram Dass Jee International Airport, Amritsar"})
m00 = Airport.create! ({ :iata => "ATR", :name => "Atar International Airport"})
m00 = Airport.create! ({ :iata => "ATZ", :name => "Assiut International Airport"})
m00 = Airport.create! ({ :iata => "AUA", :name => "Queen Beatrix International Airport"})
m00 = Airport.create! ({ :iata => "AUH", :name => "Abu Dhabi International Airport"})
m00 = Airport.create! ({ :iata => "AUS", :name => "Austin Bergstrom International Airport"})
m00 = Airport.create! ({ :iata => "AVP", :name => "Wilkes Barre Scranton International Airport"})
m00 = Airport.create! ({ :iata => "AYT", :name => "Antalya International Airport"})
m00 = Airport.create! ({ :iata => "AZO", :name => "Kalamazoo Battle Creek International Airport"})
m00 = Airport.create! ({ :iata => "BAH", :name => "Bahrain International Airport"})
m00 = Airport.create! ({ :iata => "BAQ", :name => "Ernesto Cortissoz International Airport"})
m00 = Airport.create! ({ :iata => "BBU", :name => "B?neasa International Airport"})
m00 = Airport.create! ({ :iata => "BCD", :name => "Bacolod-Silay City International Airport"})
m00 = Airport.create! ({ :iata => "BCN", :name => "Barcelona International Airport"})
m00 = Airport.create! ({ :iata => "BDA", :name => "L.F. Wade International International Airport"})
m00 = Airport.create! ({ :iata => "BDL", :name => "Bradley International Airport"})
m00 = Airport.create! ({ :iata => "BDO", :name => "Husein Sastranegara International Airport"})
m00 = Airport.create! ({ :iata => "BEN", :name => "Benina International Airport"})
m00 = Airport.create! ({ :iata => "BEY", :name => "Beirut Rafic Hariri International Airport"})
m00 = Airport.create! ({ :iata => "BFI", :name => "Boeing Field King County International Airport"})
m00 = Airport.create! ({ :iata => "BFN", :name => "J B M Hertzog International Airport"})
m00 = Airport.create! ({ :iata => "BFS", :name => "Belfast International Airport"})
m00 = Airport.create! ({ :iata => "BGF", :name => "Bangui M Poko International Airport"})
m00 = Airport.create! ({ :iata => "BGI", :name => "Sir Grantley Adams International Airport"})
m00 = Airport.create! ({ :iata => "BGR", :name => "Bangor International Airport"})
m00 = Airport.create! ({ :iata => "BHM", :name => "Birmingham-Shuttlesworth International Airport"})
m00 = Airport.create! ({ :iata => "BHX", :name => "Birmingham International Airport"})
m00 = Airport.create! ({ :iata => "BIL", :name => "Billings Logan International Airport"})
m00 = Airport.create! ({ :iata => "BJL", :name => "Banjul International Airport"})
m00 = Airport.create! ({ :iata => "BJM", :name => "Bujumbura International Airport"})
m00 = Airport.create! ({ :iata => "BJV", :name => "Milas Bodrum International Airport"})
m00 = Airport.create! ({ :iata => "BKI", :name => "Kota Kinabalu International Airport"})
m00 = Airport.create! ({ :iata => "BLA", :name => "General Jose Antonio Anzoategui International Airport"})
m00 = Airport.create! ({ :iata => "BLI", :name => "Bellingham International Airport"})
m00 = Airport.create! ({ :iata => "BLK", :name => "Blackpool International Airport"})
m00 = Airport.create! ({ :iata => "BLR", :name => "Bengaluru International Airport"})
m00 = Airport.create! ({ :iata => "BLZ", :name => "Chileka International Airport"})
m00 = Airport.create! ({ :iata => "BME", :name => "Broome International Airport"})
m00 = Airport.create! ({ :iata => "BNA", :name => "Nashville International Airport"})
m00 = Airport.create! ({ :iata => "BND", :name => "Bandar Abbas International Airport"})
m00 = Airport.create! ({ :iata => "BNE", :name => "Brisbane International Airport"})
m00 = Airport.create! ({ :iata => "BNX", :name => "Banja Luka International Airport"})
m00 = Airport.create! ({ :iata => "BOC", :name => "Bocas Del Toro International Airport"})
m00 = Airport.create! ({ :iata => "BOG", :name => "El Dorado International Airport"})
m00 = Airport.create! ({ :iata => "BOM", :name => "Chhatrapati Shivaji International Airport"})
m00 = Airport.create! ({ :iata => "BON", :name => "Flamingo International Airport"})
m00 = Airport.create! ({ :iata => "BOS", :name => "General Edward Lawrence Logan International Airport"})
m00 = Airport.create! ({ :iata => "BPN", :name => "Sepinggan International Airport"})
m00 = Airport.create! ({ :iata => "BRI", :name => "Bari / Palese International Airport"})
m00 = Airport.create! ({ :iata => "BRM", :name => "Barquisimeto International Airport"})
m00 = Airport.create! ({ :iata => "BRO", :name => "Brownsville South Padre Island International Airport"})
m00 = Airport.create! ({ :iata => "BRS", :name => "Bristol International Airport"})
m00 = Airport.create! ({ :iata => "BRX", :name => "Maria Montez International Airport"})
m00 = Airport.create! ({ :iata => "BSB", :name => "Presidente Juscelino Kubistschek International Airport"})
m00 = Airport.create! ({ :iata => "BSR", :name => "Basrah International Airport"})
m00 = Airport.create! ({ :iata => "BTE", :name => "Sherbro International Airport"})
m00 = Airport.create! ({ :iata => "BTV", :name => "Burlington International Airport"})
m00 = Airport.create! ({ :iata => "BUD", :name => "Budapest Listz Ferenc international Airport"})
m00 = Airport.create! ({ :iata => "BUF", :name => "Buffalo Niagara International Airport"})
m00 = Airport.create! ({ :iata => "BUQ", :name => "Joshua Mqabuko Nkomo International Airport"})
m00 = Airport.create! ({ :iata => "BUS", :name => "Batumi International Airport"})
m00 = Airport.create! ({ :iata => "BWI", :name => "Baltimore/Washington International Thurgood Marshal Airport"})
m00 = Airport.create! ({ :iata => "BWN", :name => "Brunei International Airport"})
m00 = Airport.create! ({ :iata => "BYJ", :name => "Beja International Airport"})
m00 = Airport.create! ({ :iata => "BZE", :name => "Philip S. W. Goldson International Airport"})
m00 = Airport.create! ({ :iata => "BZY", :name => "Balti International Airport"})
m00 = Airport.create! ({ :iata => "CAI", :name => "Cairo International Airport"})
m00 = Airport.create! ({ :iata => "CAN", :name => "Guangzhou Baiyun International Airport"})
m00 = Airport.create! ({ :iata => "CAP", :name => "Cap Haitien International Airport"})
m00 = Airport.create! ({ :iata => "CAR", :name => "Carmelo International Airport"})
m00 = Airport.create! ({ :iata => "CBB", :name => "Jorge Wilsterman International Airport"})
m00 = Airport.create! ({ :iata => "CBQ", :name => "Margaret Ekpo International Airport"})
m00 = Airport.create! ({ :iata => "CBR", :name => "Canberra International Airport"})
m00 = Airport.create! ({ :iata => "CCJ", :name => "Calicut International Airport"})
m00 = Airport.create! ({ :iata => "CCU", :name => "Netaji Subhash Chandra Bose International Airport"})
m00 = Airport.create! ({ :iata => "CDG", :name => "Charles de Gaulle International Airport"})
m00 = Airport.create! ({ :iata => "CEB", :name => "Mactan Cebu International Airport"})
m00 = Airport.create! ({ :iata => "CEI", :name => "Chiang Rai International Airport"})
m00 = Airport.create! ({ :iata => "CFU", :name => "Ioannis Kapodistrias International Airport"})
m00 = Airport.create! ({ :iata => "CGK", :name => "Soekarno-Hatta International Airport"})
m00 = Airport.create! ({ :iata => "CGP", :name => "Shah Amanat International Airport"})
m00 = Airport.create! ({ :iata => "CHC", :name => "Christchurch International Airport"})
m00 = Airport.create! ({ :iata => "CHQ", :name => "Chania International Airport"})
m00 = Airport.create! ({ :iata => "CHS", :name => "Charleston Air Force Base-International Airport"})
m00 = Airport.create! ({ :iata => "CIU", :name => "Chippewa County International Airport"})
m00 = Airport.create! ({ :iata => "CIX", :name => "Capitan FAP Jose A Quinones Gonzales International Airport"})
m00 = Airport.create! ({ :iata => "CJB", :name => "Coimbatore International Airport"})
m00 = Airport.create! ({ :iata => "CJJ", :name => "Cheongju International Airport"})
m00 = Airport.create! ({ :iata => "CJU", :name => "Jeju International Airport"})
m00 = Airport.create! ({ :iata => "CKC", :name => "Cherkasy International Airport"})
m00 = Airport.create! ({ :iata => "CKG", :name => "Chongqing Jiangbei International Airport"})
m00 = Airport.create! ({ :iata => "CLE", :name => "Cleveland Hopkins International Airport"})
m00 = Airport.create! ({ :iata => "CLJ", :name => "Cluj-Napoca International Airport"})
m00 = Airport.create! ({ :iata => "CLM", :name => "William R Fairchild International Airport"})
m00 = Airport.create! ({ :iata => "CLO", :name => "Alfonso Bonilla Aragon International Airport"})
m00 = Airport.create! ({ :iata => "CLT", :name => "Charlotte Douglas International Airport"})
m00 = Airport.create! ({ :iata => "CMB", :name => "Bandaranaike International Colombo Airport"})
m00 = Airport.create! ({ :iata => "CME", :name => "Ciudad del Carmen International Airport"})
m00 = Airport.create! ({ :iata => "CMH", :name => "Port Columbus International Airport"})
m00 = Airport.create! ({ :iata => "CMN", :name => "Mohammed V International Airport"})
m00 = Airport.create! ({ :iata => "CMW", :name => "Ignacio Agramonte International Airport"})
m00 = Airport.create! ({ :iata => "CND", :name => "Mihail Kog?lniceanu International Airport"})
m00 = Airport.create! ({ :iata => "CNF", :name => "Tancredo Neves International Airport"})
m00 = Airport.create! ({ :iata => "CNS", :name => "Cairns International Airport"})
m00 = Airport.create! ({ :iata => "CNX", :name => "Chiang Mai International Airport"})
m00 = Airport.create! ({ :iata => "COK", :name => "Cochin International Airport"})
m00 = Airport.create! ({ :iata => "CPR", :name => "Casper-Natrona County International Airport"})
m00 = Airport.create! ({ :iata => "CPT", :name => "Cape Town International Airport"})
m00 = Airport.create! ({ :iata => "CRK", :name => "Diosdado Macapagal International Airport"})
m00 = Airport.create! ({ :iata => "CRP", :name => "Corpus Christi International Airport"})
m00 = Airport.create! ({ :iata => "CTM", :name => "Chetumal International Airport"})
m00 = Airport.create! ({ :iata => "CTU", :name => "Chengdu Shuangliu International Airport"})
m00 = Airport.create! ({ :iata => "CUC", :name => "Camilo Daza International Airport"})
m00 = Airport.create! ({ :iata => "CUL", :name => "Federal de Bachigualato International Airport"})
m00 = Airport.create! ({ :iata => "CUR", :name => "Hato International Airport"})
m00 = Airport.create! ({ :iata => "CUU", :name => "General Roberto Fierro Villalobos International Airport"})
m00 = Airport.create! ({ :iata => "CUZ", :name => "Alejandro Velasco Astete International Airport"})
m00 = Airport.create! ({ :iata => "CVG", :name => "Cincinnati Northern Kentucky International Airport"})
m00 = Airport.create! ({ :iata => "CVM", :name => "General Pedro Jose Mendez International Airport"})
m00 = Airport.create! ({ :iata => "CWC", :name => "Chernivtsi International Airport"})
m00 = Airport.create! ({ :iata => "CWF", :name => "Chennault International Airport"})
m00 = Airport.create! ({ :iata => "CWL", :name => "Cardiff International Airport"})
m00 = Airport.create! ({ :iata => "CXI", :name => "Cassidy International Airport"})
m00 = Airport.create! ({ :iata => "CYB", :name => "Gerrard Smith International Airport"})
m00 = Airport.create! ({ :iata => "CYO", :name => "Vilo Acuna International Airport"})
m00 = Airport.create! ({ :iata => "CYR", :name => "Laguna de Los Patos International Airport"})
m00 = Airport.create! ({ :iata => "CZA", :name => "Chichen Itza International Airport"})
m00 = Airport.create! ({ :iata => "CZL", :name => "Mohamed Boudiaf International Airport"})
m00 = Airport.create! ({ :iata => "CZM", :name => "Cozumel International Airport"})
m00 = Airport.create! ({ :iata => "DAB", :name => "Daytona Beach International Airport"})
m00 = Airport.create! ({ :iata => "DAC", :name => "Dhaka / Hazrat Shahjalal International Airport"})
m00 = Airport.create! ({ :iata => "DAD", :name => "Da Nang International Airport"})
m00 = Airport.create! ({ :iata => "DAM", :name => "Damascus International Airport"})
m00 = Airport.create! ({ :iata => "DAR", :name => "Mwalimu Julius K. Nyerere International Airport"})
m00 = Airport.create! ({ :iata => "DAV", :name => "Enrique Malek International Airport"})
m00 = Airport.create! ({ :iata => "DAY", :name => "James M Cox Dayton International Airport"})
m00 = Airport.create! ({ :iata => "DBB", :name => "El Alamein International Airport"})
m00 = Airport.create! ({ :iata => "DEB", :name => "Debrecen International Airport"})
m00 = Airport.create! ({ :iata => "DEL", :name => "Indira Gandhi International Airport"})
m00 = Airport.create! ({ :iata => "DEN", :name => "Denver International Airport"})
m00 = Airport.create! ({ :iata => "DFW", :name => "Dallas Fort Worth International Airport"})
m00 = Airport.create! ({ :iata => "DGO", :name => "General Guadalupe Victoria International Airport"})
m00 = Airport.create! ({ :iata => "DIL", :name => "Presidente Nicolau Lobato International Airport"})
m00 = Airport.create! ({ :iata => "DIR", :name => "Aba Tenna Dejazmach Yilma International Airport"})
m00 = Airport.create! ({ :iata => "DJE", :name => "Djerba Zarzis International Airport"})
m00 = Airport.create! ({ :iata => "DLA", :name => "Douala International Airport"})
m00 = Airport.create! ({ :iata => "DLH", :name => "Duluth International Airport"})
m00 = Airport.create! ({ :iata => "DLM", :name => "Dalaman International Airport"})
m00 = Airport.create! ({ :iata => "DME", :name => "Domodedovo International Airport"})
m00 = Airport.create! ({ :iata => "DMK", :name => "Don Mueang International Airport"})
m00 = Airport.create! ({ :iata => "DMM", :name => "King Fahd International Airport"})
m00 = Airport.create! ({ :iata => "DNK", :name => "Dnipropetrovsk International Airport"})
m00 = Airport.create! ({ :iata => "DOH", :name => "Doha International Airport"})
m00 = Airport.create! ({ :iata => "DOK", :name => "Donetsk International Airport"})
m00 = Airport.create! ({ :iata => "DPS", :name => "Ngurah Rai (Bali) International Airport"})
m00 = Airport.create! ({ :iata => "DRW", :name => "Darwin International Airport"})
m00 = Airport.create! ({ :iata => "DSM", :name => "Des Moines International Airport"})
m00 = Airport.create! ({ :iata => "DUR", :name => "King Shaka International Airport"})
m00 = Airport.create! ({ :iata => "DVO", :name => "Francisco Bangoy International Airport"})
m00 = Airport.create! ({ :iata => "DWC", :name => "Al Maktoum International Airport"})
m00 = Airport.create! ({ :iata => "DXB", :name => "Dubai International Airport"})
m00 = Airport.create! ({ :iata => "DZA", :name => "Dzaoudzi Pamandzi International Airport"})
m00 = Airport.create! ({ :iata => "DZO", :name => "Santa Bernardina International Airport"})
m00 = Airport.create! ({ :iata => "EBB", :name => "Entebbe International Airport"})
m00 = Airport.create! ({ :iata => "EBL", :name => "Erbil International Airport"})
m00 = Airport.create! ({ :iata => "ECN", :name => "Ercan International Airport"})
m00 = Airport.create! ({ :iata => "ECP", :name => "Northwest Florida Beaches International Airport"})
m00 = Airport.create! ({ :iata => "EDL", :name => "Eldoret International Airport"})
m00 = Airport.create! ({ :iata => "EGO", :name => "Belgorod International Airport"})
m00 = Airport.create! ({ :iata => "EIS", :name => "Terrance B. Lettsome International Airport"})
m00 = Airport.create! ({ :iata => "ELP", :name => "El Paso International Airport"})
m00 = Airport.create! ({ :iata => "ENU", :name => "Akanu Ibiam International Airport"})
m00 = Airport.create! ({ :iata => "EPS", :name => "Arroyo Barril International Airport"})
m00 = Airport.create! ({ :iata => "ERI", :name => "Erie International Tom Ridge Field"})
m00 = Airport.create! ({ :iata => "ERL", :name => "Erenhot Saiwusu International Airport"})
m00 = Airport.create! ({ :iata => "ERZ", :name => "Erzurum International Airport"})
m00 = Airport.create! ({ :iata => "ESB", :name => "Esenbo?a International Airport"})
m00 = Airport.create! ({ :iata => "EVN", :name => "Zvartnots International Airport"})
m00 = Airport.create! ({ :iata => "EWR", :name => "Newark Liberty International Airport"})
m00 = Airport.create! ({ :iata => "EXT", :name => "Exeter International Airport"})
m00 = Airport.create! ({ :iata => "EYW", :name => "Key West International Airport"})
m00 = Airport.create! ({ :iata => "EZE", :name => "Ministro Pistarini International Airport"})
m00 = Airport.create! ({ :iata => "FAI", :name => "Fairbanks International Airport"})
m00 = Airport.create! ({ :iata => "FAR", :name => "Hector International Airport"})
m00 = Airport.create! ({ :iata => "FAT", :name => "Fresno Yosemite International Airport"})
m00 = Airport.create! ({ :iata => "FBM", :name => "Lubumbashi International Airport"})
m00 = Airport.create! ({ :iata => "FCA", :name => "Glacier Park International Airport"})
m00 = Airport.create! ({ :iata => "FCO", :name => "Leonardo Da Vinci (Fiumicino) International Airport"})
m00 = Airport.create! ({ :iata => "FIH", :name => "Ndjili International Airport"})
m00 = Airport.create! ({ :iata => "FJR", :name => "Fujairah International Airport"})
m00 = Airport.create! ({ :iata => "FKI", :name => "Bangoka International Airport"})
m00 = Airport.create! ({ :iata => "FLL", :name => "Fort Lauderdale Hollywood International Airport"})
m00 = Airport.create! ({ :iata => "FNA", :name => "Lungi International Airport"})
m00 = Airport.create! ({ :iata => "FNJ", :name => "Sunan International Airport"})
m00 = Airport.create! ({ :iata => "FNT", :name => "Bishop International Airport"})
m00 = Airport.create! ({ :iata => "FOC", :name => "Fuzhou Changle International Airport"})
m00 = Airport.create! ({ :iata => "FOR", :name => "Pinto Martins International Airport"})
m00 = Airport.create! ({ :iata => "FPO", :name => "Grand Bahama International Airport"})
m00 = Airport.create! ({ :iata => "FPR", :name => "St Lucie County International Airport"})
m00 = Airport.create! ({ :iata => "FRA", :name => "Frankfurt am Main International Airport"})
m00 = Airport.create! ({ :iata => "FRS", :name => "Mundo Maya International Airport"})
m00 = Airport.create! ({ :iata => "FRU", :name => "Manas International Airport"})
m00 = Airport.create! ({ :iata => "FTW", :name => "Fort Worth Meacham International Airport"})
m00 = Airport.create! ({ :iata => "FUN", :name => "Funafuti International Airport"})
m00 = Airport.create! ({ :iata => "FWA", :name => "Fort Wayne International Airport"})
m00 = Airport.create! ({ :iata => "GAF", :name => "Gafsa Ksar International Airport"})
m00 = Airport.create! ({ :iata => "GAN", :name => "Gan International Airport"})
m00 = Airport.create! ({ :iata => "GAU", :name => "Lokpriya Gopinath Bordoloi International Airport"})
m00 = Airport.create! ({ :iata => "GBB", :name => "Gabala International Airport"})
m00 = Airport.create! ({ :iata => "GBE", :name => "Sir Seretse Khama International Airport"})
m00 = Airport.create! ({ :iata => "GCM", :name => "Owen Roberts International Airport"})
m00 = Airport.create! ({ :iata => "GDL", :name => "Don Miguel Hidalgo Y Costilla International Airport"})
m00 = Airport.create! ({ :iata => "GDT", :name => "JAGS McCartney International Airport"})
m00 = Airport.create! ({ :iata => "GEG", :name => "Spokane International Airport"})
m00 = Airport.create! ({ :iata => "GEO", :name => "Cheddi Jagan International Airport"})
m00 = Airport.create! ({ :iata => "GES", :name => "General Santos International Airport"})
m00 = Airport.create! ({ :iata => "GFK", :name => "Grand Forks International Airport"})
m00 = Airport.create! ({ :iata => "GGT", :name => "Exuma International Airport"})
m00 = Airport.create! ({ :iata => "GGW", :name => "Wokal Field Glasgow International Airport"})
m00 = Airport.create! ({ :iata => "GLA", :name => "Glasgow International Airport"})
m00 = Airport.create! ({ :iata => "GLS", :name => "Scholes International At Galveston Airport"})
m00 = Airport.create! ({ :iata => "GMO", :name => "Gombe Lawanti International Airport"})
m00 = Airport.create! ({ :iata => "GMP", :name => "Gimpo International Airport"})
m00 = Airport.create! ({ :iata => "GND", :name => "Point Salines International Airport"})
m00 = Airport.create! ({ :iata => "GOJ", :name => "Nizhny Novgorod International Airport"})
m00 = Airport.create! ({ :iata => "GOM", :name => "Goma International Airport"})
m00 = Airport.create! ({ :iata => "GOU", :name => "Garoua International Airport"})
m00 = Airport.create! ({ :iata => "GPT", :name => "Gulfport Biloxi International Airport"})
m00 = Airport.create! ({ :iata => "GRB", :name => "Austin Straubel International Airport"})
m00 = Airport.create! ({ :iata => "GRR", :name => "Gerald R. Ford International Airport"})
m00 = Airport.create! ({ :iata => "GSO", :name => "Piedmont Triad International Airport"})
m00 = Airport.create! ({ :iata => "GSP", :name => "Greenville Spartanburg International Airport"})
m00 = Airport.create! ({ :iata => "GSQ", :name => "Shark El Oweinat International Airport"})
m00 = Airport.create! ({ :iata => "GTF", :name => "Great Falls International Airport"})
m00 = Airport.create! ({ :iata => "GUM", :name => "Antonio B. Won Pat International Airport"})
m00 = Airport.create! ({ :iata => "GVA", :name => "Geneva Cointrin International Airport"})
m00 = Airport.create! ({ :iata => "GWD", :name => "Gwadar International Airport"})
m00 = Airport.create! ({ :iata => "GXF", :name => "Sayun International Airport"})
m00 = Airport.create! ({ :iata => "GYD", :name => "Heydar Aliyev International Airport"})
m00 = Airport.create! ({ :iata => "GYE", :name => "Simon Bolivar International Airport"})
m00 = Airport.create! ({ :iata => "GYY", :name => "Gary Chicago International Airport"})
m00 = Airport.create! ({ :iata => "GZA", :name => "Yasser Arafat International Airport"})
m00 = Airport.create! ({ :iata => "GZT", :name => "Gaziantep International Airport"})
m00 = Airport.create! ({ :iata => "HAH", :name => "Prince Said Ibrahim International Airport"})
m00 = Airport.create! ({ :iata => "HAK", :name => "Haikou Meilan International Airport"})
m00 = Airport.create! ({ :iata => "HAN", :name => "Noi Bai International Airport"})
m00 = Airport.create! ({ :iata => "HBA", :name => "Hobart International Airport"})
m00 = Airport.create! ({ :iata => "HBE", :name => "Borg El Arab International Airport"})
m00 = Airport.create! ({ :iata => "HDY", :name => "Hat Yai International Airport"})
m00 = Airport.create! ({ :iata => "HER", :name => "Heraklion International Nikos Kazantzakis Airport"})
m00 = Airport.create! ({ :iata => "HET", :name => "Baita International Airport"})
m00 = Airport.create! ({ :iata => "HFA", :name => "Haifa International Airport"})
m00 = Airport.create! ({ :iata => "HFE", :name => "Hefei Luogang International Airport"})
m00 = Airport.create! ({ :iata => "HGA", :name => "Egal International Airport"})
m00 = Airport.create! ({ :iata => "HGH", :name => "Hangzhou Xiaoshan International Airport"})
m00 = Airport.create! ({ :iata => "HIR", :name => "Honiara International Airport"})
m00 = Airport.create! ({ :iata => "HKG", :name => "Chek Lap Kok International Airport"})
m00 = Airport.create! ({ :iata => "HKG", :name => "Hong Kong International Airport Kai Tak"})
m00 = Airport.create! ({ :iata => "HKT", :name => "Phuket International Airport"})
m00 = Airport.create! ({ :iata => "HLP", :name => "Halim Perdanakusuma International Airport"})
m00 = Airport.create! ({ :iata => "HLZ", :name => "Hamilton International Airport"})
m00 = Airport.create! ({ :iata => "HMB", :name => "Sohag International Airport"})
m00 = Airport.create! ({ :iata => "HMO", :name => "General Ignacio P. Garcia International Airport"})
m00 = Airport.create! ({ :iata => "HND", :name => "Tokyo International Airport"})
m00 = Airport.create! ({ :iata => "HNL", :name => "Honolulu International Airport"})
m00 = Airport.create! ({ :iata => "HOD", :name => "Hodeidah International Airport"})
m00 = Airport.create! ({ :iata => "HOG", :name => "Frank Pais International Airport"})
m00 = Airport.create! ({ :iata => "HPH", :name => "Cat Bi International Airport"})
m00 = Airport.create! ({ :iata => "HRE", :name => "Harare International Airport"})
m00 = Airport.create! ({ :iata => "HRG", :name => "Hurghada International Airport"})
m00 = Airport.create! ({ :iata => "HRK", :name => "Kharkiv International Airport"})
m00 = Airport.create! ({ :iata => "HRL", :name => "Valley International Airport"})
m00 = Airport.create! ({ :iata => "HSV", :name => "Huntsville International Carl T Jones Field"})
m00 = Airport.create! ({ :iata => "HUF", :name => "Terre Haute International Hulman Field"})
m00 = Airport.create! ({ :iata => "HYD", :name => "Rajiv Gandhi International Airport, Shamshabad"})
m00 = Airport.create! ({ :iata => "IAD", :name => "Washington Dulles International Airport"})
m00 = Airport.create! ({ :iata => "IAG", :name => "Niagara Falls International Airport"})
m00 = Airport.create! ({ :iata => "IAH", :name => "George Bush Intercontinental Houston Airport"})
m00 = Airport.create! ({ :iata => "ICN", :name => "Incheon International Airport"})
m00 = Airport.create! ({ :iata => "IEV", :name => "Kiev Zhuliany International Airport"})
m00 = Airport.create! ({ :iata => "IFN", :name => "Esfahan Shahid Beheshti International Airport"})
m00 = Airport.create! ({ :iata => "IFO", :name => "Ivano-Frankivsk International Airport"})
m00 = Airport.create! ({ :iata => "IFP", :name => "Laughlin Bullhead International Airport"})
m00 = Airport.create! ({ :iata => "IGU", :name => "Cataratas International Airport"})
m00 = Airport.create! ({ :iata => "IKA", :name => "Imam Khomeini International Airport"})
m00 = Airport.create! ({ :iata => "ILM", :name => "Wilmington International Airport"})
m00 = Airport.create! ({ :iata => "ILO", :name => "Iloilo International Airport"})
m00 = Airport.create! ({ :iata => "ILR", :name => "Ilorin International Airport"})
m00 = Airport.create! ({ :iata => "IND", :name => "Indianapolis International Airport"})
m00 = Airport.create! ({ :iata => "INL", :name => "Falls International Airport"})
m00 = Airport.create! ({ :iata => "INU", :name => "Nauru International Airport"})
m00 = Airport.create! ({ :iata => "IQT", :name => "Coronel FAP Francisco Secada Vignetta International Airport"})
m00 = Airport.create! ({ :iata => "ISB", :name => "Benazir Bhutto International Airport"})
m00 = Airport.create! ({ :iata => "ITM", :name => "Osaka International Airport"})
m00 = Airport.create! ({ :iata => "ITO", :name => "Hilo International Airport"})
m00 = Airport.create! ({ :iata => "IUE", :name => "Niue International Airport"})
m00 = Airport.create! ({ :iata => "IXE", :name => "Mangalore International Airport"})
m00 = Airport.create! ({ :iata => "IXZ", :name => "Vir Savarkar International Airport"})
m00 = Airport.create! ({ :iata => "JAI", :name => "Jaipur International Airport"})
m00 = Airport.create! ({ :iata => "JAN", :name => "Jackson Evers International Airport"})
m00 = Airport.create! ({ :iata => "JAX", :name => "Jacksonville International Airport"})
m00 = Airport.create! ({ :iata => "JBQ", :name => "La Isabela International Airport"})
m00 = Airport.create! ({ :iata => "JED", :name => "King Abdulaziz International Airport"})
m00 = Airport.create! ({ :iata => "JFK", :name => "John F Kennedy International Airport"})
m00 = Airport.create! ({ :iata => "JHB", :name => "Senai International Airport"})
m00 = Airport.create! ({ :iata => "JNB", :name => "OR Tambo International Airport"})
m00 = Airport.create! ({ :iata => "JNU", :name => "Juneau International Airport"})
m00 = Airport.create! ({ :iata => "JOG", :name => "Adi Sutjipto International Airport"})
m00 = Airport.create! ({ :iata => "JRO", :name => "Kilimanjaro International Airport"})
m00 = Airport.create! ({ :iata => "JUJ", :name => "Gobernador Horacio Guzman International Airport"})
m00 = Airport.create! ({ :iata => "JUL", :name => "Inca Manco Capac International Airport"})
m00 = Airport.create! ({ :iata => "KAB", :name => "Kariba International Airport"})
m00 = Airport.create! ({ :iata => "KAN", :name => "Mallam Aminu International Airport"})
m00 = Airport.create! ({ :iata => "KBL", :name => "Kabul International Airport"})
m00 = Airport.create! ({ :iata => "KBP", :name => "Boryspil International Airport"})
m00 = Airport.create! ({ :iata => "KCH", :name => "Kuching International Airport"})
m00 = Airport.create! ({ :iata => "KEF", :name => "Keflavik International Airport"})
m00 = Airport.create! ({ :iata => "KGL", :name => "Kigali International Airport"})
m00 = Airport.create! ({ :iata => "KGP", :name => "Kogalym International Airport"})
m00 = Airport.create! ({ :iata => "KHH", :name => "Kaohsiung International Airport"})
m00 = Airport.create! ({ :iata => "KHI", :name => "Jinnah International Airport"})
m00 = Airport.create! ({ :iata => "KHN", :name => "Nanchang Changbei International Airport"})
m00 = Airport.create! ({ :iata => "KIA", :name => "Kaieteur International Airport"})
m00 = Airport.create! ({ :iata => "KIH", :name => "Kish International Airport"})
m00 = Airport.create! ({ :iata => "KIN", :name => "Norman Manley International Airport"})
m00 = Airport.create! ({ :iata => "KIV", :name => "Chi?in?u International Airport"})
m00 = Airport.create! ({ :iata => "KIX", :name => "Kansai International Airport"})
m00 = Airport.create! ({ :iata => "KLO", :name => "Kalibo International Airport"})
m00 = Airport.create! ({ :iata => "KLV", :name => "Karlovy Vary International Airport"})
m00 = Airport.create! ({ :iata => "KMG", :name => "Kunming Wujiaba International Airport"})
m00 = Airport.create! ({ :iata => "KOA", :name => "Kona International At Keahole Airport"})
m00 = Airport.create! ({ :iata => "KOS", :name => "Sihanoukville International Airport"})
m00 = Airport.create! ({ :iata => "KQT", :name => "Qurghonteppa International Airport"})
m00 = Airport.create! ({ :iata => "KRR", :name => "Krasnodar International Airport"})
m00 = Airport.create! ({ :iata => "KRT", :name => "Khartoum International Airport"})
m00 = Airport.create! ({ :iata => "KSA", :name => "Kosrae International Airport"})
m00 = Airport.create! ({ :iata => "KTM", :name => "Tribhuvan International Airport"})
m00 = Airport.create! ({ :iata => "KTN", :name => "Ketchikan International Airport"})
m00 = Airport.create! ({ :iata => "KTW", :name => "Katowice International Airport"})
m00 = Airport.create! ({ :iata => "KUF", :name => "Kurumoch International Airport"})
m00 = Airport.create! ({ :iata => "KUL", :name => "Kuala Lumpur International Airport"})
m00 = Airport.create! ({ :iata => "KUN", :name => "Kaunas International Airport"})
m00 = Airport.create! ({ :iata => "KVA", :name => "Alexander the Great International Airport"})
m00 = Airport.create! ({ :iata => "KWG", :name => "Kryvyi Rih International Airport"})
m00 = Airport.create! ({ :iata => "KWI", :name => "Kuwait International Airport"})
m00 = Airport.create! ({ :iata => "KWL", :name => "Guilin Liangjiang International Airport"})
m00 = Airport.create! ({ :iata => "KZN", :name => "Kazan International Airport"})
m00 = Airport.create! ({ :iata => "LAO", :name => "Laoag International Airport"})
m00 = Airport.create! ({ :iata => "LAS", :name => "McCarran International Airport"})
m00 = Airport.create! ({ :iata => "LAX", :name => "Los Angeles International Airport"})
m00 = Airport.create! ({ :iata => "LBB", :name => "Lubbock Preston Smith International Airport"})
m00 = Airport.create! ({ :iata => "LCA", :name => "Larnaca International Airport"})
m00 = Airport.create! ({ :iata => "LCE", :name => "Goloson International Airport"})
m00 = Airport.create! ({ :iata => "LGK", :name => "Langkawi International Airport"})
m00 = Airport.create! ({ :iata => "LGP", :name => "Legazpi City International Airport"})
m00 = Airport.create! ({ :iata => "LHE", :name => "Alama Iqbal International Airport"})
m00 = Airport.create! ({ :iata => "LIO", :name => "Limon International Airport"})
m00 = Airport.create! ({ :iata => "LIR", :name => "Daniel Oduber Quiros International Airport"})
m00 = Airport.create! ({ :iata => "LKO", :name => "Chaudhary Charan Singh International Airport"})
m00 = Airport.create! ({ :iata => "LLW", :name => "Lilongwe International Airport"})
m00 = Airport.create! ({ :iata => "LMM", :name => "Valle del Fuerte International Airport"})
m00 = Airport.create! ({ :iata => "LOP", :name => "Bandara International Lombok Airport"})
m00 = Airport.create! ({ :iata => "LOS", :name => "Murtala Muhammed International Airport"})
m00 = Airport.create! ({ :iata => "LOV", :name => "Monclova International Airport"})
m00 = Airport.create! ({ :iata => "LPB", :name => "El Alto International Airport"})
m00 = Airport.create! ({ :iata => "LPQ", :name => "Luang Phabang International Airport"})
m00 = Airport.create! ({ :iata => "LPX", :name => "Liep?ja International Airport"})
m00 = Airport.create! ({ :iata => "LRD", :name => "Laredo International Airport"})
m00 = Airport.create! ({ :iata => "LRL", :name => "Niamtougou International Airport"})
m00 = Airport.create! ({ :iata => "LRM", :name => "Casa De Campo International Airport"})
m00 = Airport.create! ({ :iata => "LRU", :name => "Las Cruces International Airport"})
m00 = Airport.create! ({ :iata => "LSP", :name => "Josefa Camejo International Airport"})
m00 = Airport.create! ({ :iata => "LTK", :name => "Bassel Al-Assad International Airport"})
m00 = Airport.create! ({ :iata => "LTO", :name => "Loreto International Airport"})
m00 = Airport.create! ({ :iata => "LTX", :name => "Cotopaxi International Airport"})
m00 = Airport.create! ({ :iata => "LUN", :name => "Lusaka International Airport"})
m00 = Airport.create! ({ :iata => "LUX", :name => "Luxembourg-Findel International Airport"})
m00 = Airport.create! ({ :iata => "LWO", :name => "Lviv International Airport"})
m00 = Airport.create! ({ :iata => "LXR", :name => "Luxor International Airport"})
m00 = Airport.create! ({ :iata => "LYP", :name => "Faisalabad International Airport"})
m00 = Airport.create! ({ :iata => "MAA", :name => "Chennai International Airport"})
m00 = Airport.create! ({ :iata => "MAD", :name => "Madrid Barajas International Airport"})
m00 = Airport.create! ({ :iata => "MAF", :name => "Midland International Airport"})
m00 = Airport.create! ({ :iata => "MAJ", :name => "Marshall Islands International Airport"})
m00 = Airport.create! ({ :iata => "MAM", :name => "General Servando Canales International Airport"})
m00 = Airport.create! ({ :iata => "MAO", :name => "Eduardo Gomes International Airport"})
m00 = Airport.create! ({ :iata => "MAR", :name => "La Chinita International Airport"})
m00 = Airport.create! ({ :iata => "MBA", :name => "Mombasa Moi International Airport"})
m00 = Airport.create! ({ :iata => "MBD", :name => "Mmabatho International Airport"})
m00 = Airport.create! ({ :iata => "MBJ", :name => "Sangster International Airport"})
m00 = Airport.create! ({ :iata => "MBS", :name => "MBS International Airport"})
m00 = Airport.create! ({ :iata => "MCI", :name => "Kansas City International Airport"})
m00 = Airport.create! ({ :iata => "MCO", :name => "Orlando International Airport"})
m00 = Airport.create! ({ :iata => "MCT", :name => "Muscat International Airport"})
m00 = Airport.create! ({ :iata => "MDG", :name => "Mudanjiang Hailang International Airport"})
m00 = Airport.create! ({ :iata => "MDL", :name => "Mandalay International Airport"})
m00 = Airport.create! ({ :iata => "MDT", :name => "Harrisburg International Airport"})
m00 = Airport.create! ({ :iata => "MDW", :name => "Chicago Midway International Airport"})
m00 = Airport.create! ({ :iata => "MEC", :name => "Eloy Alfaro International Airport"})
m00 = Airport.create! ({ :iata => "MEL", :name => "Melbourne International Airport"})
m00 = Airport.create! ({ :iata => "MEM", :name => "Memphis International Airport"})
m00 = Airport.create! ({ :iata => "MER", :name => "Ricardo de Tomasi International Airport"})
m00 = Airport.create! ({ :iata => "MES", :name => "Polonia International Airport"})
m00 = Airport.create! ({ :iata => "MEX", :name => "Licenciado Benito Juarez International Airport"})
m00 = Airport.create! ({ :iata => "MFE", :name => "Mc Allen Miller International Airport"})
m00 = Airport.create! ({ :iata => "MFM", :name => "Macau International Airport"})
m00 = Airport.create! ({ :iata => "MFR", :name => "Rogue Valley International Medford Airport"})
m00 = Airport.create! ({ :iata => "MGA", :name => "Augusto C. Sandino (Managua) International Airport"})
m00 = Airport.create! ({ :iata => "MGQ", :name => "Aden Adde International Airport"})
m00 = Airport.create! ({ :iata => "MHD", :name => "Mashhad International Airport"})
m00 = Airport.create! ({ :iata => "MHH", :name => "Marsh Harbour International Airport"})
m00 = Airport.create! ({ :iata => "MIA", :name => "Miami International Airport"})
m00 = Airport.create! ({ :iata => "MIR", :name => "Monastir Habib Bourguiba International Airport"})
m00 = Airport.create! ({ :iata => "MIU", :name => "Maiduguri International Airport"})
m00 = Airport.create! ({ :iata => "MJG", :name => "Areopuerto Internacional Michael Gonzalez"})
m00 = Airport.create! ({ :iata => "MJT", :name => "Mytilene International Airport"})
m00 = Airport.create! ({ :iata => "MKE", :name => "General Mitchell International Airport"})
m00 = Airport.create! ({ :iata => "MLB", :name => "Melbourne International Airport"})
m00 = Airport.create! ({ :iata => "MLI", :name => "Quad City International Airport"})
m00 = Airport.create! ({ :iata => "MLM", :name => "General Francisco J. Mujica International Airport"})
m00 = Airport.create! ({ :iata => "MLZ", :name => "Cerro Largo International Airport"})
m00 = Airport.create! ({ :iata => "MNL", :name => "Ninoy Aquino International Airport"})
m00 = Airport.create! ({ :iata => "MOT", :name => "Minot International Airport"})
m00 = Airport.create! ({ :iata => "MPW", :name => "Mariupol International Airport"})
m00 = Airport.create! ({ :iata => "MQF", :name => "Magnitogorsk International Airport"})
m00 = Airport.create! ({ :iata => "MQP", :name => "Kruger Mpumalanga International Airport"})
m00 = Airport.create! ({ :iata => "MRU", :name => "Sir Seewoosagur Ramgoolam International Airport"})
m00 = Airport.create! ({ :iata => "MSE", :name => "Kent International Airport"})
m00 = Airport.create! ({ :iata => "MSO", :name => "Missoula International Airport"})
m00 = Airport.create! ({ :iata => "MSP", :name => "Minneapolis-St Paul International/Wold-Chamberlain Airport"})
m00 = Airport.create! ({ :iata => "MSQ", :name => "Minsk International Airport"})
m00 = Airport.create! ({ :iata => "MSS", :name => "Massena International Richards Field"})
m00 = Airport.create! ({ :iata => "MSU", :name => "Moshoeshoe I International Airport"})
m00 = Airport.create! ({ :iata => "MSW", :name => "Massawa International Airport"})
m00 = Airport.create! ({ :iata => "MSY", :name => "Louis Armstrong New Orleans International Airport"})
m00 = Airport.create! ({ :iata => "MTY", :name => "General Mariano Escobedo International Airport"})
m00 = Airport.create! ({ :iata => "MUC", :name => "Munich International Airport"})
m00 = Airport.create! ({ :iata => "MUX", :name => "Multan International Airport"})
m00 = Airport.create! ({ :iata => "MVB", :name => "M Vengue El Hadj Omar Bongo Ondimba International Airport"})
m00 = Airport.create! ({ :iata => "MVD", :name => "Carrasco International /General C L Berisso Airport"})
m00 = Airport.create! ({ :iata => "MVZ", :name => "Masvingo International Airport"})
m00 = Airport.create! ({ :iata => "MXP", :name => "Malpensa International Airport"})
m00 = Airport.create! ({ :iata => "MYR", :name => "Myrtle Beach International Airport"})
m00 = Airport.create! ({ :iata => "MZT", :name => "General Rafael Buelna International Airport"})
m00 = Airport.create! ({ :iata => "NAG", :name => "Dr. Babasaheb Ambedkar International Airport"})
m00 = Airport.create! ({ :iata => "NAN", :name => "Nadi International Airport"})
m00 = Airport.create! ({ :iata => "NAS", :name => "Lynden Pindling International Airport"})
m00 = Airport.create! ({ :iata => "NAV", :name => "Nev?ehir Kapadokya International Airport"})
m00 = Airport.create! ({ :iata => "NBE", :name => "Enfidha Zine El Abidine Ben Ali International Airport"})
m00 = Airport.create! ({ :iata => "NBO", :name => "Jomo Kenyatta International Airport"})
m00 = Airport.create! ({ :iata => "NDB", :name => "Nouadhibou International Airport"})
m00 = Airport.create! ({ :iata => "NDJ", :name => "N'Djamena International Airport"})
m00 = Airport.create! ({ :iata => "NDR", :name => "Nador International Airport"})
m00 = Airport.create! ({ :iata => "NEV", :name => "Vance W. Amory International Airport"})
m00 = Airport.create! ({ :iata => "NGB", :name => "Ningbo Lishe International Airport"})
m00 = Airport.create! ({ :iata => "NGO", :name => "Chubu Centrair International Airport"})
m00 = Airport.create! ({ :iata => "NIC", :name => "Nicosia International Airport"})
m00 = Airport.create! ({ :iata => "NIM", :name => "Diori Hamani International Airport"})
m00 = Airport.create! ({ :iata => "NKC", :name => "Nouakchott International Airport"})
m00 = Airport.create! ({ :iata => "NLK", :name => "Norfolk Island International Airport"})
m00 = Airport.create! ({ :iata => "NLV", :name => "Mykolaiv International Airport"})
m00 = Airport.create! ({ :iata => "NOG", :name => "Nogales International Airport"})
m00 = Airport.create! ({ :iata => "NOU", :name => "La Tontouta International Airport"})
m00 = Airport.create! ({ :iata => "NRT", :name => "Narita International Airport"})
m00 = Airport.create! ({ :iata => "NTR", :name => "Del Norte International Airport"})
m00 = Airport.create! ({ :iata => "NTY", :name => "Pilanesberg International Airport"})
m00 = Airport.create! ({ :iata => "NVT", :name => "Ministro Victor Konder International Airport"})
m00 = Airport.create! ({ :iata => "NWI", :name => "Norwich International Airport"})
m00 = Airport.create! ({ :iata => "OAK", :name => "Metropolitan Oakland International Airport"})
m00 = Airport.create! ({ :iata => "ODS", :name => "Odessa International Airport"})
m00 = Airport.create! ({ :iata => "OMO", :name => "Mostar International Airport"})
m00 = Airport.create! ({ :iata => "OMR", :name => "Oradea International Airport"})
m00 = Airport.create! ({ :iata => "ONT", :name => "Ontario International Airport"})
m00 = Airport.create! ({ :iata => "ORD", :name => "Chicago O'Hare International Airport"})
m00 = Airport.create! ({ :iata => "ORF", :name => "Norfolk International Airport"})
m00 = Airport.create! ({ :iata => "OSB", :name => "Mosul International Airport"})
m00 = Airport.create! ({ :iata => "OSO", :name => "Sulaymaniyah International Airport"})
m00 = Airport.create! ({ :iata => "OST", :name => "Ostend-Bruges International Airport"})
m00 = Airport.create! ({ :iata => "OTP", :name => "Henri Coand? International Airport"})
m00 = Airport.create! ({ :iata => "OXB", :name => "Osvaldo Vieira International Airport"})
m00 = Airport.create! ({ :iata => "OZH", :name => "Zaporizhzhia International Airport"})
m00 = Airport.create! ({ :iata => "PAC", :name => "Marcos A. Gelabert International Airport"})
m00 = Airport.create! ({ :iata => "PAP", :name => "Toussaint Louverture International Airport"})
m00 = Airport.create! ({ :iata => "PBG", :name => "Plattsburgh International Airport"})
m00 = Airport.create! ({ :iata => "PBI", :name => "Palm Beach International Airport"})
m00 = Airport.create! ({ :iata => "PBL", :name => "General Bartolome Salom International Airport"})
m00 = Airport.create! ({ :iata => "PBM", :name => "Johan Adolf Pengel International Airport"})
m00 = Airport.create! ({ :iata => "PCL", :name => "Cap FAP David Abenzur Rengifo International Airport"})
m00 = Airport.create! ({ :iata => "PDP", :name => "Capitan Corbeta CA Curbelo International Airport"})
m00 = Airport.create! ({ :iata => "PDS", :name => "Piedras Negras International Airport"})
m00 = Airport.create! ({ :iata => "PDV", :name => "Plovdiv International Airport"})
m00 = Airport.create! ({ :iata => "PDX", :name => "Portland International Airport"})
m00 = Airport.create! ({ :iata => "PEK", :name => "Beijing Capital International Airport"})
m00 = Airport.create! ({ :iata => "PEM", :name => "Padre Aldamiz International Airport"})
m00 = Airport.create! ({ :iata => "PEN", :name => "Penang International Airport"})
m00 = Airport.create! ({ :iata => "PER", :name => "Perth International Airport"})
m00 = Airport.create! ({ :iata => "PEW", :name => "Peshawar International Airport"})
m00 = Airport.create! ({ :iata => "PFN", :name => "Panama City-Bay Co International Airport"})
m00 = Airport.create! ({ :iata => "PFO", :name => "Paphos International Airport"})
m00 = Airport.create! ({ :iata => "PHC", :name => "Port Harcourt International Airport"})
m00 = Airport.create! ({ :iata => "PHE", :name => "Port Hedland International Airport"})
m00 = Airport.create! ({ :iata => "PHF", :name => "Newport News Williamsburg International Airport"})
m00 = Airport.create! ({ :iata => "PHL", :name => "Philadelphia International Airport"})
m00 = Airport.create! ({ :iata => "PHX", :name => "Phoenix Sky Harbor International Airport"})
m00 = Airport.create! ({ :iata => "PIE", :name => "St Petersburg Clearwater International Airport"})
m00 = Airport.create! ({ :iata => "PIT", :name => "Pittsburgh International Airport"})
m00 = Airport.create! ({ :iata => "PJC", :name => "Dr Augusto Roberto Fuster International Airport"})
m00 = Airport.create! ({ :iata => "PKZ", :name => "Pakse International Airport"})
m00 = Airport.create! ({ :iata => "PLQ", :name => "Palanga International Airport"})
m00 = Airport.create! ({ :iata => "PNH", :name => "Phnom Penh International Airport"})
m00 = Airport.create! ({ :iata => "PNI", :name => "Pohnpei International Airport"})
m00 = Airport.create! ({ :iata => "POM", :name => "Port Moresby Jacksons International Airport"})
m00 = Airport.create! ({ :iata => "POP", :name => "Gregorio Luperon International Airport"})
m00 = Airport.create! ({ :iata => "POS", :name => "Piarco International Airport"})
m00 = Airport.create! ({ :iata => "PPG", :name => "Pago Pago International Airport"})
m00 = Airport.create! ({ :iata => "PPT", :name => "Faa'a International Airport"})
m00 = Airport.create! ({ :iata => "PQM", :name => "Palenque International Airport"})
m00 = Airport.create! ({ :iata => "PRG", :name => "Ruzyn? International Airport"})
m00 = Airport.create! ({ :iata => "PSA", :name => "Pisa / San Giusto - Galileo Galilei International Airport"})
m00 = Airport.create! ({ :iata => "PSM", :name => "Portsmouth International at Pease Airport"})
m00 = Airport.create! ({ :iata => "PSP", :name => "Palm Springs International Airport"})
m00 = Airport.create! ({ :iata => "PSR", :name => "Pescara International Airport"})
m00 = Airport.create! ({ :iata => "PTG", :name => "Polokwane International Airport"})
m00 = Airport.create! ({ :iata => "PTY", :name => "Tocumen International Airport"})
m00 = Airport.create! ({ :iata => "PUJ", :name => "Punta Cana International Airport"})
m00 = Airport.create! ({ :iata => "PUS", :name => "Gimhae International Airport"})
m00 = Airport.create! ({ :iata => "PVG", :name => "Shanghai Pudong International Airport"})
m00 = Airport.create! ({ :iata => "PWM", :name => "Portland International Jetport Airport"})
m00 = Airport.create! ({ :iata => "PXM", :name => "Puerto Escondido International Airport"})
m00 = Airport.create! ({ :iata => "PZO", :name => "General Manuel Carlos Piar International Airport"})
m00 = Airport.create! ({ :iata => "PZU", :name => "Port Sudan New International Airport"})
m00 = Airport.create! ({ :iata => "QOW", :name => "Sam Mbakwe International Airport"})
m00 = Airport.create! ({ :iata => "RAI", :name => "Praia International Airport"})
m00 = Airport.create! ({ :iata => "RAR", :name => "Rarotonga International Airport"})
m00 = Airport.create! ({ :iata => "RDU", :name => "Raleigh Durham International Airport"})
m00 = Airport.create! ({ :iata => "REC", :name => "Guararapes - Gilberto Freyre International Airport"})
m00 = Airport.create! ({ :iata => "REP", :name => "Angkor International Airport"})
m00 = Airport.create! ({ :iata => "RES", :name => "Resistencia International Airport"})
m00 = Airport.create! ({ :iata => "REX", :name => "General Lucio Blanco International Airport"})
m00 = Airport.create! ({ :iata => "RFD", :name => "Chicago Rockford International Airport"})
m00 = Airport.create! ({ :iata => "RGA", :name => "Hermes Quijada International Airport"})
m00 = Airport.create! ({ :iata => "RGN", :name => "Yangon International Airport"})
m00 = Airport.create! ({ :iata => "RIC", :name => "Richmond International Airport"})
m00 = Airport.create! ({ :iata => "RIX", :name => "Riga International Airport"})
m00 = Airport.create! ({ :iata => "RIY", :name => "Mukalla International Airport"})
m00 = Airport.create! ({ :iata => "RKT", :name => "Ras Al Khaimah International Airport"})
m00 = Airport.create! ({ :iata => "RLO", :name => "Valle Del Conlara International Airport"})
m00 = Airport.create! ({ :iata => "RMF", :name => "Marsa Alam International Airport"})
m00 = Airport.create! ({ :iata => "RMI", :name => "Rimini / Miramare - Federico Fellini International Airport"})
m00 = Airport.create! ({ :iata => "RNO", :name => "Reno Tahoe International Airport"})
m00 = Airport.create! ({ :iata => "ROB", :name => "Roberts International Airport"})
m00 = Airport.create! ({ :iata => "ROC", :name => "Greater Rochester International Airport"})
m00 = Airport.create! ({ :iata => "ROP", :name => "Rota International Airport"})
m00 = Airport.create! ({ :iata => "ROW", :name => "Roswell International Air Center Airport"})
m00 = Airport.create! ({ :iata => "RST", :name => "Rochester International Airport"})
m00 = Airport.create! ({ :iata => "RSW", :name => "Southwest Florida International Airport"})
m00 = Airport.create! ({ :iata => "RTB", :name => "Juan Manuel Galvez International Airport"})
m00 = Airport.create! ({ :iata => "RUH", :name => "King Khaled International Airport"})
m00 = Airport.create! ({ :iata => "RVY", :name => "Presidente General Don Oscar D. Gestido International Airport"})
m00 = Airport.create! ({ :iata => "RWN", :name => "Rivne International Airport"})
m00 = Airport.create! ({ :iata => "SAH", :name => "Sana a International Airport"})
m00 = Airport.create! ({ :iata => "SAL", :name => "El Salvador International Airport"})
m00 = Airport.create! ({ :iata => "SAN", :name => "San Diego International Airport"})
m00 = Airport.create! ({ :iata => "SAT", :name => "San Antonio International Airport"})
m00 = Airport.create! ({ :iata => "SAV", :name => "Savannah Hilton Head International Airport"})
m00 = Airport.create! ({ :iata => "SBZ", :name => "Sibiu International Airport"})
m00 = Airport.create! ({ :iata => "SCT", :name => "Socotra International Airport"})
m00 = Airport.create! ({ :iata => "SCU", :name => "Antonio Maceo International Airport"})
m00 = Airport.create! ({ :iata => "SDA", :name => "Baghdad International Airport"})
m00 = Airport.create! ({ :iata => "SDF", :name => "Louisville International Standiford Field"})
m00 = Airport.create! ({ :iata => "SEA", :name => "Seattle Tacoma International Airport"})
m00 = Airport.create! ({ :iata => "SEZ", :name => "Seychelles International Airport"})
m00 = Airport.create! ({ :iata => "SFA", :name => "Sfax Thyna International Airport"})
m00 = Airport.create! ({ :iata => "SFB", :name => "Orlando Sanford International Airport"})
m00 = Airport.create! ({ :iata => "SFH", :name => "San Felipe International Airport"})
m00 = Airport.create! ({ :iata => "SFO", :name => "San Francisco International Airport"})
m00 = Airport.create! ({ :iata => "SFS", :name => "Subic Bay International Airport"})
m00 = Airport.create! ({ :iata => "SGN", :name => "Tan Son Nhat International Airport"})
m00 = Airport.create! ({ :iata => "SHA", :name => "Shanghai Hongqiao International Airport"})
m00 = Airport.create! ({ :iata => "SHJ", :name => "Sharjah International Airport"})
m00 = Airport.create! ({ :iata => "SIN", :name => "Singapore Changi International Airport"})
m00 = Airport.create! ({ :iata => "SIP", :name => "Simferopol International Airport"})
m00 = Airport.create! ({ :iata => "SJC", :name => "Norman Y. Mineta San Jose International Airport"})
m00 = Airport.create! ({ :iata => "SJD", :name => "Los Cabos International Airport"})
m00 = Airport.create! ({ :iata => "SJJ", :name => "Sarajevo International Airport"})
m00 = Airport.create! ({ :iata => "SJO", :name => "Juan Santamaria International Airport"})
m00 = Airport.create! ({ :iata => "SJU", :name => "Luis Munoz Marin International Airport"})
m00 = Airport.create! ({ :iata => "SJW", :name => "Shijiazhuang Daguocun International Airport"})
m00 = Airport.create! ({ :iata => "SKB", :name => "Robert L. Bradshaw International Airport"})
m00 = Airport.create! ({ :iata => "SKG", :name => "Thessaloniki Macedonia International Airport"})
m00 = Airport.create! ({ :iata => "SKO", :name => "Sadiq Abubakar III International Airport"})
m00 = Airport.create! ({ :iata => "SKV", :name => "St Catherine International Airport"})
m00 = Airport.create! ({ :iata => "SLA", :name => "Martin Miguel De Guemes International Airport"})
m00 = Airport.create! ({ :iata => "SLC", :name => "Salt Lake City International Airport"})
m00 = Airport.create! ({ :iata => "SLP", :name => "Ponciano Arriaga International Airport"})
m00 = Airport.create! ({ :iata => "SLW", :name => "Plan De Guadalupe International Airport"})
m00 = Airport.create! ({ :iata => "SLZ", :name => "Marechal Cunha Machado International Airport"})
m00 = Airport.create! ({ :iata => "SMF", :name => "Sacramento International Airport"})
m00 = Airport.create! ({ :iata => "SON", :name => "Santo Pekoa International Airport"})
m00 = Airport.create! ({ :iata => "SPN", :name => "Francisco C. Ada Saipan International Airport"})
m00 = Airport.create! ({ :iata => "SRQ", :name => "Sarasota Bradenton International Airport"})
m00 = Airport.create! ({ :iata => "SSH", :name => "Sharm El Sheikh International Airport"})
m00 = Airport.create! ({ :iata => "STD", :name => "Mayor Buenaventura Vivas International Airport"})
m00 = Airport.create! ({ :iata => "STI", :name => "Cibao International Airport"})
m00 = Airport.create! ({ :iata => "STL", :name => "Lambert St Louis International Airport"})
m00 = Airport.create! ({ :iata => "STY", :name => "Nueva Hesperides International Airport"})
m00 = Airport.create! ({ :iata => "SUB", :name => "Juanda International Airport"})
m00 = Airport.create! ({ :iata => "SUV", :name => "Nausori International Airport"})
m00 = Airport.create! ({ :iata => "SVO", :name => "Sheremetyevo International Airport"})
m00 = Airport.create! ({ :iata => "SWF", :name => "Stewart International Airport"})
m00 = Airport.create! ({ :iata => "SXM", :name => "Princess Juliana International Airport"})
m00 = Airport.create! ({ :iata => "SYD", :name => "Sydney Kingsford Smith International Airport"})
m00 = Airport.create! ({ :iata => "SYQ", :name => "Tobias Bolanos International Airport"})
m00 = Airport.create! ({ :iata => "SYR", :name => "Syracuse Hancock International Airport"})
m00 = Airport.create! ({ :iata => "SYX", :name => "Sanya Phoenix International Airport"})
m00 = Airport.create! ({ :iata => "SYZ", :name => "Shiraz Shahid Dastghaib International Airport"})
m00 = Airport.create! ({ :iata => "SZB", :name => "Sultan Abdul Aziz Shah International Airport"})
m00 = Airport.create! ({ :iata => "SZX", :name => "Shenzhen Bao'an International Airport"})
m00 = Airport.create! ({ :iata => "SZY", :name => "Szczytno-Szymany International Airport"})
m00 = Airport.create! ({ :iata => "TAI", :name => "Ta izz International Airport"})
m00 = Airport.create! ({ :iata => "TAM", :name => "General Francisco Javier Mina International Airport"})
m00 = Airport.create! ({ :iata => "TAP", :name => "Tapachula International Airport"})
m00 = Airport.create! ({ :iata => "TAS", :name => "Tashkent International Airport"})
m00 = Airport.create! ({ :iata => "TBS", :name => "Tbilisi International Airport"})
m00 = Airport.create! ({ :iata => "TBU", :name => "Fua amotu International Airport"})
m00 = Airport.create! ({ :iata => "TBZ", :name => "Tabriz International Airport"})
m00 = Airport.create! ({ :iata => "TCP", :name => "Taba International Airport"})
m00 = Airport.create! ({ :iata => "TCQ", :name => "Coronel FAP Carlos Ciriani Santa Rosa International Airport"})
m00 = Airport.create! ({ :iata => "THF", :name => "Berlin-Tempelhof International Airport"})
m00 = Airport.create! ({ :iata => "THR", :name => "Mehrabad International Airport"})
m00 = Airport.create! ({ :iata => "TIA", :name => "Tirana International Airport Mother Teresa"})
m00 = Airport.create! ({ :iata => "TIP", :name => "Tripoli International Airport"})
m00 = Airport.create! ({ :iata => "TIQ", :name => "Tinian International Airport"})
m00 = Airport.create! ({ :iata => "TJM", :name => "Roshchino International Airport"})
m00 = Airport.create! ({ :iata => "TJP", :name => "Areopuerto Internacional Michael Gonzalez"})
m00 = Airport.create! ({ :iata => "TKK", :name => "Chuuk International Airport"})
m00 = Airport.create! ({ :iata => "TLC", :name => "Licenciado Adolfo Lopez Mateos International Airport"})
m00 = Airport.create! ({ :iata => "TLV", :name => "Ben Gurion International Airport"})
m00 = Airport.create! ({ :iata => "TNL", :name => "Ternopil International Airport"})
m00 = Airport.create! ({ :iata => "TOE", :name => "Tozeur Nefta International Airport"})
m00 = Airport.create! ({ :iata => "TPA", :name => "Tampa International Airport"})
m00 = Airport.create! ({ :iata => "TPE", :name => "Taiwan Taoyuan International Airport"})
m00 = Airport.create! ({ :iata => "TRC", :name => "Francisco Sarabia International Airport"})
m00 = Airport.create! ({ :iata => "TRN", :name => "Torino / Caselle International Airport"})
m00 = Airport.create! ({ :iata => "TRU", :name => "Capitan FAP Carlos Martinez De Pinillos International Airport"})
m00 = Airport.create! ({ :iata => "TRV", :name => "Trivandrum International Airport"})
m00 = Airport.create! ({ :iata => "TRW", :name => "Bonriki International Airport"})
m00 = Airport.create! ({ :iata => "TSE", :name => "Astana International Airport"})
m00 = Airport.create! ({ :iata => "TSN", :name => "Tianjin Binhai International Airport"})
m00 = Airport.create! ({ :iata => "TUK", :name => "Turbat International Airport"})
m00 = Airport.create! ({ :iata => "TUL", :name => "Tulsa International Airport"})
m00 = Airport.create! ({ :iata => "TUN", :name => "Tunis Carthage International Airport"})
m00 = Airport.create! ({ :iata => "TUS", :name => "Tucson International Airport"})
m00 = Airport.create! ({ :iata => "TXL", :name => "Berlin-Tegel International Airport"})
m00 = Airport.create! ({ :iata => "TXN", :name => "Tunxi International Airport"})
m00 = Airport.create! ({ :iata => "TZL", :name => "Tuzla International Airport"})
m00 = Airport.create! ({ :iata => "TZX", :name => "Trabzon International Airport"})
m00 = Airport.create! ({ :iata => "UDJ", :name => "Uzhhorod International Airport"})
m00 = Airport.create! ({ :iata => "UET", :name => "Quetta International Airport"})
m00 = Airport.create! ({ :iata => "UFA", :name => "Ufa International Airport"})
m00 = Airport.create! ({ :iata => "UIO", :name => "Mariscal Sucre International Airport"})
m00 = Airport.create! ({ :iata => "ULN", :name => "Chinggis Khaan International Airport"})
m00 = Airport.create! ({ :iata => "UNI", :name => "Union Island International Airport"})
m00 = Airport.create! ({ :iata => "UPG", :name => "Hasanuddin International Airport"})
m00 = Airport.create! ({ :iata => "UTP", :name => "U-Tapao International Airport"})
m00 = Airport.create! ({ :iata => "UVF", :name => "Hewanorra International Airport"})
m00 = Airport.create! ({ :iata => "VAV", :name => "Vava u International Airport"})
m00 = Airport.create! ({ :iata => "VCL", :name => "Chu Lai International Airport"})
m00 = Airport.create! ({ :iata => "VCP", :name => "Viracopos International Airport"})
m00 = Airport.create! ({ :iata => "VDA", :name => "Ovda International Airport"})
m00 = Airport.create! ({ :iata => "VER", :name => "General Heriberto Jara International Airport"})
m00 = Airport.create! ({ :iata => "VFA", :name => "Victoria Falls International Airport"})
m00 = Airport.create! ({ :iata => "VIE", :name => "Vienna International Airport"})
m00 = Airport.create! ({ :iata => "VKO", :name => "Vnukovo International Airport"})
m00 = Airport.create! ({ :iata => "VLN", :name => "Arturo Michelena International Airport"})
m00 = Airport.create! ({ :iata => "VNO", :name => "Vilnius International Airport"})
m00 = Airport.create! ({ :iata => "VNT", :name => "Ventspils International Airport"})
m00 = Airport.create! ({ :iata => "VOG", :name => "Volgograd International Airport"})
m00 = Airport.create! ({ :iata => "VOZ", :name => "Voronezh International Airport"})
m00 = Airport.create! ({ :iata => "VRA", :name => "Juan Gualberto Gomez International Airport"})
m00 = Airport.create! ({ :iata => "VSG", :name => "Luhansk International Airport"})
m00 = Airport.create! ({ :iata => "VTE", :name => "Wattay International Airport"})
m00 = Airport.create! ({ :iata => "VVI", :name => "Viru Viru International Airport"})
m00 = Airport.create! ({ :iata => "VVO", :name => "Vladivostok International Airport"})
m00 = Airport.create! ({ :iata => "WDH", :name => "Hosea Kutako International Airport"})
m00 = Airport.create! ({ :iata => "WLG", :name => "Wellington International Airport"})
m00 = Airport.create! ({ :iata => "WRZ", :name => "Weerawila International Airport"})
m00 = Airport.create! ({ :iata => "WUH", :name => "Wuhan Tianhe International Airport"})
m00 = Airport.create! ({ :iata => "WUX", :name => "Sunan Shuofang International Airport"})
m00 = Airport.create! ({ :iata => "WWK", :name => "Wewak International Airport"})
m00 = Airport.create! ({ :iata => "XIY", :name => "Xi an Xianyang International Airport"})
m00 = Airport.create! ({ :iata => "XMN", :name => "Xiamen Gaoqi International Airport"})
m00 = Airport.create! ({ :iata => "YAP", :name => "Yap International Airport"})
m00 = Airport.create! ({ :iata => "YEG", :name => "Edmonton International Airport"})
m00 = Airport.create! ({ :iata => "YEH", :name => "Persian Gulf International Airport"})
m00 = Airport.create! ({ :iata => "YHM", :name => "John C. Munro Hamilton International Airport"})
m00 = Airport.create! ({ :iata => "YHZ", :name => "Halifax / Stanfield International Airport"})
m00 = Airport.create! ({ :iata => "YMX", :name => "Montreal International (Mirabel) Airport"})
m00 = Airport.create! ({ :iata => "YNY", :name => "Yangyang International Airport"})
m00 = Airport.create! ({ :iata => "YOW", :name => "Ottawa Macdonald-Cartier International Airport"})
m00 = Airport.create! ({ :iata => "YQB", :name => "Quebec Jean Lesage International Airport"})
m00 = Airport.create! ({ :iata => "YQM", :name => "Greater Moncton International Airport"})
m00 = Airport.create! ({ :iata => "YQR", :name => "Regina International Airport"})
m00 = Airport.create! ({ :iata => "YQX", :name => "Gander International Airport"})
m00 = Airport.create! ({ :iata => "YTM", :name => "La Macaza / Mont-Tremblant International Inc Airport"})
m00 = Airport.create! ({ :iata => "YUL", :name => "Montreal / Pierre Elliott Trudeau International Airport"})
m00 = Airport.create! ({ :iata => "YUM", :name => "Yuma MCAS/Yuma International Airport"})
m00 = Airport.create! ({ :iata => "YVR", :name => "Vancouver International Airport"})
m00 = Airport.create! ({ :iata => "YWG", :name => "Winnipeg / James Armstrong Richardson International Airport"})
m00 = Airport.create! ({ :iata => "YXE", :name => "Saskatoon John G. Diefenbaker International Airport"})
m00 = Airport.create! ({ :iata => "YXY", :name => "Whitehorse / Erik Nielsen International Airport"})
m00 = Airport.create! ({ :iata => "YYC", :name => "Calgary International Airport"})
m00 = Airport.create! ({ :iata => "YYJ", :name => "Victoria International Airport"})
m00 = Airport.create! ({ :iata => "YYT", :name => "St Johns International Airport"})
m00 = Airport.create! ({ :iata => "YYZ", :name => "Lester B. Pearson International Airport"})
m00 = Airport.create! ({ :iata => "ZAH", :name => "Zahedan International Airport"})
m00 = Airport.create! ({ :iata => "ZAM", :name => "Zamboanga International Airport"})
m00 = Airport.create! ({ :iata => "ZCL", :name => "General Leobardo C. Ruiz International Airport"})
m00 = Airport.create! ({ :iata => "ZIH", :name => "Ixtapa Zihuatanejo International Airport"})
m00 = Airport.create! ({ :iata => "ZIN", :name => "Interlaken Air Base"})
m00 = Airport.create! ({ :iata => "ZLO", :name => "Playa De Oro International Airport"})
m00 = Airport.create! ({ :iata => "ZQN", :name => "Queenstown International Airport"})
m00 = Airport.create! ({ :iata => "ZTU", :name => "Zaqatala International Airport"})
m00 = Airport.create! ({ :iata => "ZYL", :name => "Osmany International Airport"})